# docker-compose.yml

version: '3.8'
services:
  # web:
  #   build: .
  #   command: npm run start:dev
  #   volumes:
  #     - .:/code
  #   ports:
  #   - "9000:9000"
  #   environment:
  #     - DATABASE_URL="postgresql://postgres:postgres@localhost:5432/clique-db?schema=public"
  #   depends_on:
  #     - db

  db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db

volumes:
  postgres: