export default Object.freeze({
    LOGIN: 'Login',
    MEMBER: 'Members',
    REGISTER: 'Register',
    SETTING: 'Setting',
    WELCOME: 'Welcome',
    VIEW_PROFILE: 'Profile',
    HOME: 'Home',
    CREATE_TASK: 'Create Task',
    CONFIRM_CODE: 'ConfirmCode',
    NOTIFICATIONS: 'Notifications',
    ACCOUNT_VIEW_PROFILE: 'User Profile',
    CREATE_GROUP: 'Create Group',
    NOTIFICATION_SETTING: 'Notification',
    EDIT_PROFILE: 'Edit',
    PROFILE_SETTING: 'Setting',
})
