export default Object.freeze({
    LOGIN: 'Login',
    MEMBER: 'Members',
    SIGN_UP: 'Signup',
    SETTING: 'Setting',
    WELCOME: 'Welcome',
    VIEW_PROFILE: 'Profile',
    HOME: 'Home',
    CREATE_TASK: 'CreateTask',
    CONFIRM_CODE: 'ConfirmCode',
    NOTIFICATIONS: 'Notifications',
    ACCOUNT_VIEW_PROFILE: 'UserProfile',
    CREATE_GROUP: 'CreateGroup',
    NOTIFICATION_SETTING: 'Notification',
    EDIT_PROFILE: 'Edit',
    PROFILE_SETTING: 'Setting',
})