name: Build and Push Docker Image to DigitalOcean

on:
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: 'Deployment environment'     
  #       required: true
  #       default: 'prod'
  push:
    branches:
      - main # or your default branch

defaults:
  run:
    working-directory: ./server

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project Software with NestJS server...
      run: echo "Build project Software with NestJS server..."
    
    - name: Install doctl
      run: |
        curl -sL https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz | tar -xzv
        sudo mv doctl /usr/local/bin/

    - name: Login to DigitalOcean
      run: |
        export DIGITALOCEAN_ACCESS_TOKEN=${{ secrets.DO_ACCESS_TOKEN }}
        doctl auth switch --context clique
        doctl registry login
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}

    - name: Build docker image
      run: docker build -t "clique-prod" .

    - name: Tag docker image
      run: |
        docker tag "clique-prod" "registry.digitalocean.com/software-images/clique-prod:latest"

    - name: Push docker image
      run: docker push "registry.digitalocean.com/software-images/clique-prod:latest"

