name: Build and Push Docker Image to DigitalOcean

on:
  push:
    branches:
      - main # or your default branch

defaults:
  run:
    working-directory: ./server

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Build project Software with NestJS server...
      run: echo "Build project Software with NestJS server..."
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_ACCESS_TOKEN }}

    
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600


    - name: Build docker image
      run: docker build -t "clique-dev" .

    - name: Tag docker image
      run: |
        docker tag "clique-dev" "registry.digitalocean.com/software-images/clique-dev"

    - name: Push docker image
      run: docker push "registry.digitalocean.com/software-images/clique-dev:latest"

